name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: apt-get update
        run: sudo apt-get update -y

      - name: set up python
        uses: actions/setup-python@v4
        with:
          cache: "pip"
          python-version: ${{ matrix.python-version }}
          cache-dependency-path: "pyproject.toml"

      - name: install
        run: pip install -e '.[dev]'

      - name: lint
        run: inv lint

      - name: test
        run: inv test

      - name: upload coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
